#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     lineL,          sensorI2CCustom)
#pragma config(Sensor, S3,     irL,            sensorI2CCustom)
#pragma config(Sensor, S4,     lineR,          sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     driveR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     driveL,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     spinner,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    autoArm,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    liftR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    liftL,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h"
#include "hitechnic-colour-v1.h"
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


//Encoder values
int driveToLineLength = 500;
int driveToLineLengthOffset = 300;
int nudgeAmount = 400;
int turnAmount = 3000;
int rampAmount = 1000;

int waitTime = 0;
float driveMult = 1.0;

//Line Sensor variables
int redL = 0;
int greenL = 0;
int blueL = 0;
int redR = 0;
int greenR = 0;
int blueR = 0;

//IRSeeker variables
int dir_left = 0;
int S1_left, S2_left, S3_left, S4_left, S5_left = 0;
tHTIRS2DSPMode _mode = DSP_1200;

bool leftSide = true;
bool retraceSteps = false;

void selectMode();
void driveToLine();
void followLine();
void driveToEnd();
void turnOntoRamp();
void score();
bool leftOn();
bool rightOn();
void startSensors(tHTIRS2DSPMode mode);

void initializeRobot() {
	startSensors(_mode);
  return;
}

task readSensors() {
	while(true) {
		dir_left = HTIRS2readACDir(irL);
		HTIRS2readAllDCStrength(irL, S1_left, S2_left, S3_left, S4_left, S5_left);
		HTCSreadRGB(lineL, redL, greenL, blueL);
		HTCSreadRGB(lineR, redR, greenR, blueR);
	}
}

task main() {
	disableDiagnosticsDisplay();
	//selectMode();
  initializeRobot();
  StartTask(readSensors);
  waitForStart();
  //wait1Msec(waitTime);
  //driveToLine();
  followLine();
  //driveToEnd();
  //turnOntoRamp();
}

void driveToLine() {
	nMotorEncoder[driveL] = 0;
	nMotorEncoder[driveR] = 0;
	if(!leftSide) {
		driveToLineLength += driveToLineLengthOffset;
	}
	while( (abs(nMotorEncoder[driveL]) + abs(nMotorEncoder[driveR])) / 2.0 <= driveToLineLength) {
		if(leftSide) {
			motor[driveL] = motor[driveR] = 100;
		} else {
			motor[driveL] = motor[driveR] = -100;
		}
	}
	motor[driveL] = motor[driveR] = 0;
}

void followLine() {
	if(leftSide) {
		driveMult = 1.0;
	} else {
		driveMult = -1.0;
	}

	while(S3_left < 70) {
		if(leftOn() && rightOn()) {
			motor[driveL] = motor[driveR] = driveMult * 35;
		}
		if(leftOn() && !rightOn()) {
			motor[driveR] = driveMult * 30;
			motor[driveL] = driveMult * 0;
		}
		if(!leftOn() && rightOn()) {
			motor[driveR] = driveMult * 0;
			motor[driveL] = driveMult * 30;
		}
		if(!leftOn() && !rightOn()) {
			break;
		}
	}

	motor[driveL] = motor[driveR] = 0;
	score();
}

void score() {
	servo[autoArm] = 255;
	wait10Msec(100);
	servo[autoArm] = 10;
	wait10Msec(100);
}

void driveToEnd() {
	if(retraceSteps) {
		driveMult *= -1.0;
	}

	while(leftOn() || rightOn()) {
		if(leftOn() && rightOn()) {
			motor[driveL] = motor[driveR] = driveMult * 100;
		}
		if(leftOn() && !rightOn()) {
			motor[driveL] = driveMult * 0;
			motor[driveR] = driveMult * 50;
		}
		if(!leftOn() && rightOn()) {
			motor[driveL] = driveMult * 50;
			motor[driveR] = driveMult * 0;
		}
	}
	motor[driveL] = motor[driveR] = 0;
}

void turnOntoRamp() {
	nMotorEncoder[driveL] = 0;
	nMotorEncoder[driveR] = 0;
	if(leftSide && !retraceSteps) {
		while( (abs(nMotorEncoder[driveL]) + abs(nMotorEncoder[driveR])) / 2.0 < nudgeAmount) {
			motor[driveL] = motor[driveR] = 100;
		}
	}
	if(!leftSide && retraceSteps) {
		while( (abs(nMotorEncoder[driveL]) + abs(nMotorEncoder[driveR])) / 2.0 < nudgeAmount) {
			motor[driveL] = motor[driveR] = 100;
		}
	}
	nMotorEncoder[driveL] = 0;
	nMotorEncoder[driveR] = 0;
	wait1Msec(500);
	while( (abs(nMotorEncoder[driveL]) + abs(nMotorEncoder[driveR])) / 2.0 < turnAmount) {
		if(leftSide && !retraceSteps) {
			motor[driveL] = 10;
			motor[driveR] = 80;
		}
		if(leftSide && retraceSteps) {
			motor[driveL] = -10;
			motor[driveR] = -80;
		}
		if(!leftSide && !retraceSteps) {
			motor[driveL] = -10;
			motor[driveR] = -80;
		}
		if(!leftSide && retraceSteps) {
			motor[driveL] = 10;
			motor[driveR] = 80;
		}
	}
	nMotorEncoder[driveL] = 0;
	nMotorEncoder[driveR] = 0;
	while( (abs(nMotorEncoder[driveL]) + abs(nMotorEncoder[driveR])) / 2.0 < rampAmount) {
		if(leftSide && !retraceSteps) {
			motor[driveL] = motor[driveR] = 100;
		}
		if(!leftSide && retraceSteps) {
			motor[driveL] = motor[driveR] = 100;
		}
		if(leftSide && retraceSteps) {
			motor[driveL] = motor[driveR] = -100;
		}
		if(!leftSide && !retraceSteps) {
			motor[driveL] = motor[driveR] = -100;
		}
	}
	motor[driveL] = motor[driveR] = 0;
}

void startSensors(tHTIRS2DSPMode mode) {
	while(true) {
		PlaySound(soundShortBlip);
		if(HTIRS2setDSPMode(irL, mode)) {
			break;
		}
	}
}

bool leftOn() {
	if(redL > 90 || blueL > 90) {
		return true;
	} else {
		return false;
	}
}

bool rightOn() {
	if(redR > 90 || blueR > 90) {
		return true;
	} else {
		return false;
	}
}

void selectMode() {
	eraseDisplay();
	nxtDisplayCenteredTextLine(0, "Choose which way");
	nxtDisplayCenteredTextLine(1, "to drive.");
	while(nNxtButtonPressed != 3) {
		if(nNxtButtonPressed == 1) { //Right arrow
			leftSide = true;
			nxtDisplayCenteredBigTextLine(3, "Forwards");
		}
		if(nNxtButtonPressed == 2) { //Left arrow
			leftSide = false;
			nxtDisplayCenteredBigTextLine(3, "Backwards");
		}
	}
	eraseDisplay();
	nxtDisplayCenteredTextLine(0, "Do you want to");
	nxtDisplayCenteredTextLine(1, "retrace your steps?");
	wait1Msec(500);
	while(nNxtButtonPressed != 3) {
		if(nNxtButtonPressed == 1) { //Right arrow
			retraceSteps = true;
			nxtDisplayCenteredBigTextLine(3, "YES");
		}
		if(nNxtButtonPressed == 2) { //Left arrow
			retraceSteps = false;
			nxtDisplayCenteredBigTextLine(3, "NO");
		}
	}
	eraseDisplay();
	nxtDisplayCenteredTextLine(0, "How long do you");
	nxtDisplayCenteredTextLine(1, "want to wait?");
	nxtDisplayCenteredBigTextLine(2, "%d", waitTime);
	wait1Msec(500);
	while(nNxtButtonPressed != 3) {
		nxtDisplayCenteredBigTextLine(2, "%dms", waitTime);
		if(nNxtButtonPressed == 1) { //Right arrow
			waitTime += 100;
		}
		if(nNxtButtonPressed == 2) { //Left arrow
			waitTime -= 100;
		}
		if(waitTime < 0) {
			waitTime = 0;
		}
		wait1Msec(100);
	}
	eraseDisplay();
	nxtDisplayCenteredTextLine(1, "DONE");
	nxtDisplayCenteredTextLine(2, "dont forget to turn on the robot");
	nxtDisplayCenteredTextLine(3, ";)");
}
