#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     lineL,          sensorI2CCustom)
#pragma config(Sensor, S3,     irL,            sensorI2CCustom)
#pragma config(Sensor, S4,     lineR,          sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     driveR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     driveL,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     spinner,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    autoArm,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    liftR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    liftL,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h"
#include "hitechnic-colour-v1.h"
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

int driveToLineLength = 2000;

//Line Sensor variables
int redL = 0;
int greenL = 0;
int blueL = 0;
int redR = 0;
int greenR = 0;
int blueR = 0;

//IRSeeker variables
int dir_left = 0;
int S1_left, S2_left, S3_left, S4_left, S5_left = 0;
tHTIRS2DSPMode _mode = DSP_1200;

void driveToLine();
void followLine();
void driveToEnd();
void turnOntoRamp();
void score();
bool leftOn();
bool rightOn();
void startSensors(tHTIRS2DSPMode mode);

void initializeRobot() {
	startSensors(_mode);
  return;
}

task readSensors() {
	dir_left = HTIRS2readACDir(irL);
	HTIRS2readAllDCStrength(irL, S1_left, S2_left, S3_left, S4_left, S5_left);
	HTCSreadRGB(lineL, redL, greenL, blueL);
	HTCSreadRGB(lineR, redR, greenR, blueR);
}

task main() {
	disableDiagnosticsDisplay();
  initializeRobot();
  StartTask(readSensors);
  waitForStart();
  driveToLine();
  followLine();
  driveToEnd();
  turnOntoRamp();
}

void driveToLine() {
	nMotorEncoder[driveL] = 0;
	nMotorEncoder[driveR] = 0;
	while( (abs(nMotorEncoder[driveL]) + abs(nMotorEncoder[driveR])) / 2.0 <= driveToLineLength) {
		motor[driveL] = motor[driveR] = 100;
	}
	motor[driveL] = motor[driveR] = 0;
}

void followLine() {
	while(S3_left < 70) {
		if(leftOn() && rightOn()) {
			motor[driveL] = motor[driveR] = 100;
		} else if(leftOn() || rightOn()) {
			if(leftOn()) {
				motor[driveR] = 50;
				motor[driveL] = 0;
			} else {
				motor[driveL] = 50;
				motor[driveR] = 0;
			}
		}
	}

	motor[driveL] = motor[driveR] = 0;
	score();
}

void score() {
	servo[autoArm] = 255;
	wait10Msec(100);
	servo[autoArm] = 10;
	wait10Msec(100);
}

void driveToEnd() {
	while(leftOn() || rightOn()) {
		if(leftOn() && rightOn()) {
			motor[driveL] = motor[driveR] = 100;
		}
		if(leftOn() && !rightOn()) {
			motor[driveL] = 0;
			motor[driveR] = 50;
		}
		if(!leftOn() && rightOn()) {
			motor[driveL] = 50;
			motor[driveR] = 0;
		}
	}
	motor[driveL] = motor[driveR] = 0;
}

void turnOntoRamp() {

}

void startSensors(tHTIRS2DSPMode mode) {
	while(true) {
		PlaySound(soundShortBlip);
		if(HTIRS2setDSPMode(irL, mode)) {
			break;
		}
	}
}

bool leftOn() {
	if(redL > 100 || blueL > 100) {
		return true;
	}
	return false;
}

bool rightOn() {
	if(redR > 100 || blueL > 100) {
		return true;
	}
	return false;
}
